### ISSUE TITLE
Error message 

### ISSUE THREAD

**Issue by boromyr** [Mast3r0mid/TaskBarDragAndDropNoUAC#1]
The following debug message was generated while the app was running but I wasn't doing any drag and drop:
```
Le informazioni su come richiamare il debug JIT (Just-In-Time) anziché questa finestra
sono riportate in fondo al messaggio.

************** Testo dell'eccezione **************
System.ArgumentException: La larghezza e l'altezza devono essere valori non negativi.
   in System.Windows.Rect..ctor(Double x, Double y, Double width, Double height)
   in TaskBarDragAndDropNoUAC.MainForm.FindTaskbar(Int32 justtray)
   in TaskBarDragAndDropNoUAC.MainForm.MouseIsDragging_Tick(Object sender, EventArgs e)
   in System.Windows.Forms.Timer.OnTick(EventArgs e)
   in System.Windows.Forms.Timer.TimerNativeWindow.WndProc(Message& m)
   in System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)


************** Assembly caricati **************
mscorlib
    Versione assembly: 4.0.0.0
    Versione Win32: 4.8.9181.0 built by: NET481REL1LAST_C
    Base di codice: file:///C:/Windows/Microsoft.NET/Framework/v4.0.30319/mscorlib.dll
----------------------------------------
TaskBar DragAndDrop(NO UAC)
    Versione assembly: 1.0.1.0
    Versione Win32: 1.0.1
    Base di codice: file:///C:/Program%20Files/TaskBar.DragAndDrop.NO.UAC.exe
----------------------------------------
System.Windows.Forms
    Versione assembly: 4.0.0.0
    Versione Win32: 4.8.9181.0 built by: NET481REL1LAST_C
    Base di codice: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Windows.Forms/v4.0_4.0.0.0__b77a5c561934e089/System.Windows.Forms.dll
----------------------------------------
System
    Versione assembly: 4.0.0.0
    Versione Win32: 4.8.9172.0 built by: NET481REL1LAST_C
    Base di codice: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System/v4.0_4.0.0.0__b77a5c561934e089/System.dll
----------------------------------------
System.Drawing
    Versione assembly: 4.0.0.0
    Versione Win32: 4.8.9032.0 built by: NET481REL1
    Base di codice: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Drawing/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Drawing.dll
----------------------------------------


Quando il debug JIT è abilitato, tutte le eccezioni non gestite
vengono inviate al debugger JIT registrato nel computer,
anziché essere gestite da questa finestra di dialogo.

```
Windows 11 23H2

**Comment by Mast3r0mid** [comment]
Could you please consider using the [beta version](https://github.com/Mast3r0mid/TaskBarDragAndDropNoUAC/releases/tag/v.1.0.2-beta) while I investigate this issue more thoroughly to see if it still exists? I'm also planning to add more debugging structures and error handling in future versions. I value your feedback as it helps me improve.

**Comment by boromyr** [comment]
I am trying the beta version and I will communicate other debug messages if they arise.

**Comment by boromyr** [comment]
I had to restore Windows 11 using a backup due to other issues, and this is the error received from the app during its very first run on my OS.
![image](https://github.com/Mast3r0mid/TaskBarDragAndDropNoUAC/assets/52782032/3033a876-610d-4b08-a9ea-1f138c90ca2b)
```py
Le informazioni su come richiamare il debug JIT (Just-In-Time) anziché questa finestra
sono riportate in fondo al messaggio.

************** Testo dell'eccezione **************
System.Runtime.InteropServices.COMException (0x8000FFFF): Errore irreparabile (Eccezione da HRESULT: 0x8000FFFF (E_UNEXPECTED))
   in System.Runtime.InteropServices.Marshal.ThrowExceptionForHRInternal(Int32 errorCode, IntPtr errorInfo)
   in MS.Internal.Automation.UiaCoreApi.CheckError(Int32 hr)
   in MS.Internal.Automation.UiaCoreApi.UiaFind(SafeNodeHandle hnode, UiaFindParams findParams, Condition findCondition, UiaCacheRequest request)
   in System.Windows.Automation.AutomationElement.Find(TreeScope scope, Condition condition, UiaCacheRequest request, Boolean findFirst, BackgroundWorker worker)
   in System.Windows.Automation.AutomationElement.FindAll(TreeScope scope, Condition condition)
   in TaskBarDragAndDropNoUAC.MainForm.FindTaskbar(Int32 justtray)
   in TaskBarDragAndDropNoUAC.MainForm.MouseIsDragging_Tick(Object sender, EventArgs e)
   in System.Windows.Forms.Timer.OnTick(EventArgs e)
   in System.Windows.Forms.Timer.TimerNativeWindow.WndProc(Message& m)
   in System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)


************** Assembly caricati **************
mscorlib
    Versione assembly: 4.0.0.0
    Versione Win32: 4.8.9181.0 built by: NET481REL1LAST_C
    Base di codice: file:///C:/Windows/Microsoft.NET/Framework/v4.0.30319/mscorlib.dll
----------------------------------------
TaskBar DragAndDrop(NO UAC)
    Versione assembly: 1.0.2.0
    Versione Win32: 1.0.2
    Base di codice: file:///C:/Program%20Files/TaskBar.DragAndDrop.NO.UAC.exe
----------------------------------------
System.Windows.Forms
    Versione assembly: 4.0.0.0
    Versione Win32: 4.8.9181.0 built by: NET481REL1LAST_C
    Base di codice: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Windows.Forms/v4.0_4.0.0.0__b77a5c561934e089/System.Windows.Forms.dll
----------------------------------------

Quando il debug JIT è abilitato, tutte le eccezioni non gestite
vengono inviate al debugger JIT registrato nel computer,
anziché essere gestite da questa finestra di dialogo.



```

**Comment by Mast3r0mid** [comment]
What is your Windows build version? 
I've tested it on versions **22621.2361** and **22621.2428**.


 Also, which versions of the Microsoft .NET Framework are installed on your system?

 You can run this PowerShell command to see the list of installed versions.

 `Get-ChildItem 'HKLM:\SOFTWARE\Microsoft\NET Framework Setup\NDP' -Recurse | Get-ItemProperty -Name Version -ErrorAction SilentlyContinue | Where-Object { $_.PSChildName -match '^(?!S)\p{L}'} | Select-Object PSChildName, Version`

**Comment by boromyr** [comment]
OS:22635.2419


```py
PSChildName                      Version
-----------                      -------
v2.0.50727                       2.0.50727.4927
v3.0                             3.0.30729.4926
Windows Communication Foundation 3.0.4506.4926
Windows Presentation Foundation  3.0.6920.4902
v3.5                             3.5.30729.4926
Client                           4.8.09032
Full                             4.8.09032
Client                           4.0.0.0
```

**Comment by Mast3r0mid** [comment]
OS Build 22635.2419 is an Insider Preview build with some changes in Explorer.exe. 
The System.Runtime.InteropServices.COMException error is being called from MS.Internal.Automation.UiaCoreApi.UiaFind, it is related to the .NET Framework and InteropServices, not the TaskBar D&D itself. I'm afraid I can't proceed with my application based on Insider Preview Builds at this moment.

**Comment by LiquidatorFX** [comment]
> OS Build 22635.2419 is an Insider Preview build with some changes in Explorer.exe. The System.Runtime.InteropServices.COMException error is being called from MS.Internal.Automation.UiaCoreApi.UiaFind, it is related to the .NET Framework and InteropServices, not the TaskBar D&D itself. I'm afraid I can't proceed with my application based on Insider Preview Builds at this moment.

Win 11 pro 22621.2428

When the autostart parameter is set with Windows, the same error also appears

**Comment by Mast3r0mid** [comment]
I've been working on some updates for  app,  beta version (v1.0.4-beta) 

I've made a bunch of changes and improvements, and I'd love to get your help testing it out. I want to make sure any previous issues are sorted out.

This app is a passion project for me, and I'm sorry it took a bit longer to address these issues. But your input can help make it even better!

You can grab the beta version here: [v.1.0.4-beta](https://github.com/Mast3r0mid/TaskBarDragAndDropNoUAC/releases/tag/v.1.0.4-beta)

**Comment by LiquidatorFX** [comment]
> I've been working on some updates for app, beta version (v1.0.4-beta)
> 
> I've made a bunch of changes and improvements, and I'd love to get your help testing it out. I want to make sure any previous issues are sorted out.
> 
> This app is a passion project for me, and I'm sorry it took a bit longer to address these issues. But your input can help make it even better!
> 
> You can grab the beta version here: [v.1.0.4-beta](https://github.com/Mast3r0mid/TaskBarDragAndDropNoUAC/releases/tag/v.1.0.4-beta)

The 1.0.4 beta version behaves inappropriately. False opening of applications when hovering the cursor, then lack of dragging with subsequent selection of icons from the first to the opened one. Previous versions 1.0.1 and 1.03 beta worked adequately after restarting the program that crashed with a framework error

**Comment by circcc** [comment]
I tried the 1.0.4 beta version, but an error message appeared while using it. And when I drag file to the taskbar icon, an unusable mouse pointer often appears. So I'm back to 1.0.1.

**Comment by Mast3r0mid** [comment]
In the 1.0.5 beta release, I've made numerous changes to align the app's behavior with native Windows interactions. This includes updates to functions and interactions
[beta 1.0.5 is here](https://github.com/Mast3r0mid/TaskBarDragAndDropNoUAC/releases/tag/v.1.0.5-beta)

**Comment by LiquidatorFX** [comment]
> В бета-версии 1.0.5 я внес множество изменений, чтобы привести поведение приложения в соответствие со стандартными взаимодействиями Windows. Сюда входят обновления функций и взаимодействий. [Бета-версия 1.0.5 уже доступна.](https://github.com/Mast3r0mid/TaskBarDragAndDropNoUAC/releases/tag/v.1.0.5-beta)

1.04 and 1.0.5 beta - Drag and drop in the active application in the taskbar does not work if the "Automate run pinned app" checkbox is not checked:

![Снимок экрана 2023-10-18 181553](https://github.com/Mast3r0mid/TaskBarDragAndDropNoUAC/assets/88746476/9211c271-d69f-4d43-a939-5cc4c9d6a4de)


if this checkbox is enabled, then the inactive application is automatically launched, which is just annoying, since I don’t need to drag anything into the inactive applications, but I need it into the one that I have already launched, and it just happens that inactive applications are automatically opened when hovering dragging, which is completely infuriating.....

in version 1.0.1 everything works fine - with the automatic launch checkbox disabled, I can safely drag and drop files into an open application without fear that something else will be launched. However, in the latest 1.0.5 beta, when the checkbox is turned off, dragging and dropping into the active application does not work at all

**Comment by Mast3r0mid** [comment]
> > В бета-версии 1.0.5 я внес множество изменений, чтобы привести поведение приложения в соответствие со стандартными взаимодействиями Windows. Сюда входят обновления функций и взаимодействий. [Бета-версия 1.0.5 уже доступна.](https://github.com/Mast3r0mid/TaskBarDragAndDropNoUAC/releases/tag/v.1.0.5-beta)
> 
> 1.04 and 1.0.5 beta - Drag and drop in the active application in the taskbar does not work if the "Automate run pinned app" checkbox is not checked:
> 
> ![Снимок экрана 2023-10-18 181553](https://user-images.githubusercontent.com/88746476/276307698-9211c271-d69f-4d43-a939-5cc4c9d6a4de.png)
> 
> if this checkbox is enabled, then the inactive application is automatically launched, which is just annoying, since I don’t need to drag anything into the inactive applications, but I need it into the one that I have already launched, and it just happens that inactive applications are automatically opened when hovering dragging, which is completely infuriating.....
> 
> in version 1.0.1 everything works fine - with the automatic launch checkbox disabled, I can safely drag and drop files into an open application without fear that something else will be launched. However, in the latest 1.0.5 beta, when the checkbox is turned off, dragging and dropping into the active application does not work at all

i think this is because of localized windows language Pack ( as I see RU pack  ) because in EN language it works file but when i changed my windows language pack to different non-English theme and language pack i faced some new issues

could you  just check  V1.0.5 in EN Windows for me  (if possible) and if this is related to localized language pack open a new issue please ?

**Comment by circcc** [comment]
![105](https://github.com/Mast3r0mid/TaskBarDragAndDropNoUAC/assets/72944033/94b70deb-feca-4248-9aa9-51e8f9e0abd3)
1.0.5 beta not working at all.
"Automate run pinned app" is unchecked. KO Windows 11 23H2.

**Comment by Mast3r0mid** [comment]
> ![105](https://user-images.githubusercontent.com/72944033/276346744-94b70deb-feca-4248-9aa9-51e8f9e0abd3.png) 1.0.5 beta not working at all. "Automate run pinned app" is unchecked. KO Windows 11 23H2.

file changed so please check it again [v.1.0.5-beta](https://github.com/Mast3r0mid/TaskBarDragAndDropNoUAC/releases/tag/v.1.0.5-beta) and thanks for testing

**Comment by boromyr** [comment]
Unfortunately this latest version doesn't work for me either. OS in ITA

**Comment by circcc** [comment]
> file changed so please check it again [v.1.0.5-beta](https://github.com/Mast3r0mid/TaskBarDragAndDropNoUAC/releases/tag/v.1.0.5-beta) and thanks for testing

new v.1.0.5-beta(247808 byte) not working too.

**Comment by Mast3r0mid** [comment]
The initial error has been resolved, so no further action is needed on this topic. I will open a new issue related to Taskbar D&D (No UAC) not functioning correctly in (RU) and (ITA) localized versions of the operating system
