### ISSUE TITLE
not functioning correctly in localized versions of OS

### ISSUE THREAD

**Issue by Mast3r0mid** [Mast3r0mid/TaskBarDragAndDropNoUAC#3]
> В бета-версии 1.0.5 я внес множество изменений, чтобы привести поведение приложения в соответствие со стандартными взаимодействиями Windows. Сюда входят обновления функций и взаимодействий. [Бета-версия 1.0.5 уже доступна.](https://github.com/Mast3r0mid/TaskBarDragAndDropNoUAC/releases/tag/v.1.0.5-beta)

1.04 and 1.0.5 beta - Drag and drop in the active application in the taskbar does not work if the "Automate run pinned app" checkbox is not checked:

![Снимок экрана 2023-10-18 181553](https://github.com/Mast3r0mid/TaskBarDragAndDropNoUAC/assets/88746476/9211c271-d69f-4d43-a939-5cc4c9d6a4de)

if this checkbox is enabled, then the inactive application is automatically launched, which is just annoying, since I don’t need to drag anything into the inactive applications, but I need it into the one that I have already launched, and it just happens that inactive applications are automatically opened when hovering dragging, which is completely infuriating.....

in version 1.0.1 everything works fine - with the automatic launch checkbox disabled, I can safely drag and drop files into an open application without fear that something else will be launched. However, in the latest 1.0.5 beta, when the checkbox is turned off, dragging and dropping into the active application does not work at all

_Originally posted by @LiquidatorFX in https://github.com/Mast3r0mid/TaskBarDragAndDropNoUAC/issues/1#issuecomment-1768740551_

 Unfortunately this latest version doesn't work for me either. OS in ITA

_Originally posted by @boromyr in https://github.com/Mast3r0mid/TaskBarDragAndDropNoUAC/issues/1#issuecomment-1769135428_

 some other changes to support localized version of OS
 so please test this version [Beta V1.0.6](https://github.com/Mast3r0mid/TaskBarDragAndDropNoUAC/releases/tag/v.1.0.6-beta)

**Comment by circcc** [comment]
Beta V1.0.6 not working. KOR version.

**Comment by LiquidatorFX** [comment]
![Снимок экрана 2023-10-19 050714](https://github.com/Mast3r0mid/TaskBarDragAndDropNoUAC/assets/88746476/0ec9567f-1e35-49a1-8723-c125a2b29a60)

Beta V1.0.6  works fine for  ru Win 11 pro 22621.2428  but I noticed on 1.0.6 beta there is a greater load on the processor when the application is running - the processor heats up an extra 3-5 degrees...... still back to 1.0.1 - it works fine for me and drags and does not load the processor


v1.0.1
![Снимок экрана 2023-10-19 055435](https://github.com/Mast3r0mid/TaskBarDragAndDropNoUAC/assets/88746476/3fa1c1b4-af2d-4ba8-999d-9f2adc11093e)

v1.0.6 beta
![Снимок экрана 2023-10-19 055758](https://github.com/Mast3r0mid/TaskBarDragAndDropNoUAC/assets/88746476/24bbae39-ce7b-4da4-b42f-d74644e9eb70)

Anyone who knows thoroughly how his PC works and how his hardware heats up under any type of load will understand me....

**Comment by boromyr** [comment]
Beta V1.0.6 not working. IT version.

**Comment by Mast3r0mid** [comment]
> Beta V1.0.6 not working. KOR version.
@circcc

> Beta V1.0.6 not working. IT version.
@boromyr


tested on Korean OS and Italian OS , it Works, maybe you need to do 'First time Setup' or decrease 500ms auto click wait time for faster invoke msg
the only issue is high resource usage because of UI Atomation and now im trying to fix and optimize it

**Comment by circcc** [comment]
> maybe you need to do 'First time Setup'

Unlike you, I don't get the Done message when I press the OK button in the initial Setup dialog.

**Comment by boromyr** [comment]
I also don't get any message after clicking ok

**Comment by Mast3r0mid** [comment]
i just fixed both Localized windows and high CPU Temp and resource usage ( i hope so )
if you have any issue about localized OS ,refer to log console and at the beginning look for "localized String:" if its there or else please report it here and attach Log file from app Directory, 
you may download and test [beta 1.0.7](https://github.com/Mast3r0mid/TaskBarDragAndDropNoUAC/releases/tag/v.1.0.7-beta)
lots of changes 
happy testing
i will be happy to hear your opinions,
still working to improve stability and reliability

**Comment by circcc** [comment]
![1](https://github.com/Mast3r0mid/TaskBarDragAndDropNoUAC/assets/72944033/e24972f9-9f26-42b0-b658-4086f206d09e)
Beta V1.0.7 not working. Done message is displayed. 

If I turn on the log option, mouse movement becomes very slow, and it crashes after a while.

**Comment by LiquidatorFX** [comment]
Beta V1.0.7 after launch it works, but after a few minutes drag and drop stops working

**Comment by LiquidatorFX** [comment]
I don’t know about anyone, but I have the most adequate version 1.0.1 (it occasionally crashes with a framework error, but after pre-launch it can work fine for a day) - all subsequent betas do not work or work worse than the release 1.0.1

**Comment by Mast3r0mid** [comment]
@circcc i think its just for the first Icon ,right ? if that so,  fixed

and if it generally works  for localized OS , so i can close this issue and  
as @LiquidatorFX  said , there is other bug related to mouse hook and drag detection failure after while

**Comment by Mast3r0mid** [comment]
check beta 1.0.7 again :
minor new fixes :
[Beta 1.0.7](https://github.com/Mast3r0mid/TaskBarDragAndDropNoUAC/releases/tag/v.1.0.7-beta)

**Comment by boromyr** [comment]
I just tried 1.0.7 and it seems to work fine so far, 22365.2486 ita

**Comment by circcc** [comment]
new beta 1.0.7 works.
![1](https://github.com/Mast3r0mid/TaskBarDragAndDropNoUAC/assets/72944033/dbbdc33c-219c-49b1-b02c-62d9719d21fa)
However, sometimes it does not work, and in this case, it is inconvenient to have to move to the next icon and then come back.

**Comment by Mast3r0mid** [comment]
As the topic was related to the functionality of my application on localized operating systems, I'm pleased to announce that the issue has been resolved. I greatly appreciate the valuable suggestions and assistance provided. I will continue to work on improving my application over time as i know lots of bugs and issues. Thank you for your help and support.
