### ISSUE TITLE
1.0.7-Beta dont work if two or more copies of the application

### ISSUE THREAD

**Issue by LiquidatorFX** [Mast3r0mid/TaskBarDragAndDropNoUAC#4]
1.0.7-Beta Drag and drop under the icon of an open application does not work if two or more copies of the application are open under the icon

**Comment by Mast3r0mid** [comment]
i was working on it, check this 
[TaskBar DragAndDrop(NO UAC).zip](https://github.com/Mast3r0mid/TaskBarDragAndDropNoUAC/files/13064479/TaskBar.DragAndDrop.NO.UAC.zip)

**Comment by LiquidatorFX** [comment]
> i was working on it, check this [TaskBar DragAndDrop(NO UAC).zip](https://github.com/Mast3r0mid/TaskBarDragAndDropNoUAC/files/13064479/TaskBar.DragAndDrop.NO.UAC.zip)

Dont work 1.0.7 new beta 

https://github.com/Mast3r0mid/TaskBarDragAndDropNoUAC/assets/88746476/a916aead-fc62-43c1-83bf-47f18af1937a

And 1.0.1 Working fine


https://github.com/Mast3r0mid/TaskBarDragAndDropNoUAC/assets/88746476/3fe5a578-250b-479e-bf05-8a9bb53b17b8

**Comment by Mast3r0mid** [comment]
did you do the "first time setup" for new beta 1.0.7 ? im checking again
send this file please :
C:\windows\ru-RU\explorer.exe.mui

**Comment by LiquidatorFX** [comment]
[explorer.zip](https://github.com/Mast3r0mid/TaskBarDragAndDropNoUAC/files/13069436/explorer.zip)

Yes, I did a full reset and clicked install “for the first time”, it doesn’t help, if two copies of the application are running, you can’t drag it there

**Comment by Mast3r0mid** [comment]
"em Dash" in RU Os caused this issue and fixed ,
use latest release version [V1.1.0](https://github.com/Mast3r0mid/TaskBarDragAndDropNoUAC/releases/tag/Release-V1.1.0) and let me know if you have any other issue

**Comment by circcc** [comment]
V1.1.0 not working.
It does not work if there are multiple windows for one program.

**Comment by LiquidatorFX** [comment]
> "em Dash" in RU Os caused this issue and fixed , use latest release version [V1.1.0](https://github.com/Mast3r0mid/TaskBarDragAndDropNoUAC/releases/tag/Release-V1.1.0) and let me know if you have any other issue

version 1.1. - At first it seemed that it worked rather poorly: I played with different delays other than 500 ms, only the first drag and drop worked, and dragging another file again did not work..... I did a full reset to the default settings and clicked "install for the first time" "...... I repeated this procedure three times in a row just to be sure...... and the miracle seems to be working well so far, version 1.1.... I will continue testing

**Comment by Mast3r0mid** [comment]
@circcc you need to do "first time setup" as some new settings in this version, and if issue still exists please enable logging and send log file from app directly,

@LiquidatorFX i appreciate that , i may change the config file directly to app directly for easy access 
For now by default, config path is %appdata%\local\taskbardraganddrop

**Comment by circcc** [comment]
"first time setup" was used.
V1.1.0 has a lot of problems overall. Sometimes it works and sometimes it doesn't. Even if it works, there are cases where the thumbnail disappears too quickly and cannot be droped, and when the logging option is checked, the cursor sometimes moves very slowly, as if the computer is frozen. 500ms is too slow, so if I change it to 200ms, the thumbnail may appear and disappear momentarily. It is so random that it is difficult to find regularity in the problem. Even if the version goes up, the problem does not go away. 

So I will continue to use v1.0.1 which works very well.

**Comment by LiquidatorFX** [comment]
> "first time setup" was used. V1.1.0 has a lot of problems overall. Sometimes it works and sometimes it doesn't. Even if it works, there are cases where the thumbnail disappears too quickly and cannot be dragged, and when the logging option is checked, the cursor sometimes moves very slowly, as if the computer is frozen. 500ms is too slow, so if I change it to 200ms, the thumbnail may appear and disappear momentarily. It is so random that it is difficult to find regularity in the problem. Even if the version goes up, the problem does not go away.
> 
> So I will continue to use v1.0.1 which works very well.


On the new version 1.1, I also had a sudden appearance and disappearance, and when I presented the file again, the icon with two copies of the application completely failed to work, everything is exactly what you describe, but in some way incomprehensible to me, after a triple reset and a triple restart of the program at random it turns out - everything started to work normally, I myself was a little surprised by this and while I’ve been testing the new version for several hours and haven’t noticed any glitches..... tomorrow I’ll work with real tasks in the morning and then everything will be visible...

**Comment by LiquidatorFX** [comment]
v 1.1.0 and 1.1.1 - work good
